backend:
  name: git-gateway
  branch: main # or your default branch

media_folder: "../../static/images/uploads" # メディアファイルのアップロード先
public_folder: "/images/uploads" # 公開時のメディアファイルのURL

collections:
  - name: "about"
    label: "About"
    folder: "content/about"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "Body", name: "body", widget: "markdown" }
    summary: "{{body}}"

  - name: "diary"
    label: "Diary"
    folder: "content/diary"
    create: true
    slug: "{{fields.slug}}"
    media_folder: "../../static/images/diary"
    public_folder: "/images/diary"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Diaries", name: "diaries", widget: "list" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Topics", name: "topics", widget: "select", multiple: true, options: ["news", "music", "manga-and-anime", "movies-and-dramas", "comedy", "gaming", "sports", "books-and-magazines", "languages-and-foreign-cultures", "design", "internet-and-technology", "natural-science", "humanities-and-social-sciences"] }
      - { label: "Body", name: "body", widget: "markdown" }
    summary: "{{date | date('YYYY-MM-DD')}} | {{body | truncate(280, '...')}}"
    sort:
      field: "date"
      direction: "desc"

  - name: "work"
    label: "Work"
    folder: "content/work"
    create: true
    slug: "{{fields.slug}}"
    media_folder: "static/images/work"
    public_folder: "../..//images/work"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
    summary: "{{date | date('YYYY-MM-DD')}} | {{title}}"
    sort:
      field: "date"
      direction: "desc"

  - name: "keyword"
    label: "Keyword"
    folder: "content/keyword"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "Keywords", name: "keywords", widget: "list"}
      - { label: "Body", name: "body", widget: "markdown" }
    summary: "{{body | truncate(280, '...')}}　　Keyword {{keywords}}"
    sort:
      field: "body"
      direction: "asc"
