backend:
  name: git-gateway
  branch: main  # ブランチ名を指定

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "about"
    label: "About"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "works"
    label: "Works"
    folder: "content/works"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "diary"
    label: "Diary"
    folder: "content/diary"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "keyword"
    label: "Keyword"
    folder: "content/keyword"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
