/**
 * Assign list thumbnails for every column.
 * Prefers Markdown / <img> in body; otherwise cycles public/images/top.
 * Writes copies under public/images/column/{slug}.* and a generated map.
 *
 * Usage: npx tsx scripts/assign-column-thumbs.ts
 */
import fs from "node:fs";
import path from "node:path";
import { createClient } from "@supabase/supabase-js";
import dotenv from "dotenv";
import { firstImageSrc } from "../src/lib/content/html-plain";

dotenv.config({ path: ".env.local" });

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}

const sb = createClient(url, key, {
  auth: { persistSession: false, autoRefreshToken: false },
});

const ROOT = process.cwd();
const OUT_DIR = path.join(ROOT, "public/images/column");
const TOP_DIR = path.join(ROOT, "public/images/top");

const FALLBACKS = fs
  .readdirSync(TOP_DIR)
  .filter((f) => /\.(webp|jpg|jpeg|png)$/i.test(f))
  .sort((a, b) => parseInt(a, 10) - parseInt(b, 10))
  .map((f) => path.join(TOP_DIR, f));

function resolvePublicFile(src: string): string | null {
  if (!src.startsWith("/")) return null;
  const file = path.join(ROOT, "public", src.slice(1));
  return fs.existsSync(file) ? file : null;
}

async function main() {
  if (!FALLBACKS.length) {
    console.error("No fallback images in public/images/top");
    process.exit(1);
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });

  const { data, error } = await sb
    .from("column")
    .select("slug, title, body_html")
    .order("date", { ascending: false });
  if (error) throw error;

  const map: Record<string, string> = {};
  let i = 0;

  for (const row of data ?? []) {
    const slug = row.slug as string;
    const fromBody = firstImageSrc(row.body_html ?? "");
    const local = fromBody ? resolvePublicFile(fromBody) : null;
    const srcFile = local ?? FALLBACKS[i % FALLBACKS.length]!;
    if (!local) i += 1;

    const ext = path.extname(srcFile).toLowerCase() || ".webp";
    const destName = `${slug}${ext}`;
    const destFile = path.join(OUT_DIR, destName);
    fs.copyFileSync(srcFile, destFile);
    const webPath = `/images/column/${destName}`;
    map[slug] = webPath;
    console.log(
      `${slug} ← ${path.relative(ROOT, srcFile)}${local ? " (from body)" : " (fallback)"}`,
    );
  }

  const outTs = path.join(ROOT, "src/lib/content/column-thumbs.generated.ts");
  fs.writeFileSync(
    outTs,
    "/** Auto-generated by scripts/assign-column-thumbs.ts — do not edit by hand. */\n" +
      "export const COLUMN_THUMBS: Record<string, string> = " +
      JSON.stringify(map, null, 2) +
      " as const;\n",
  );
  console.log(`\nWrote ${outTs} (${Object.keys(map).length} entries)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
